name: Three-step Workflow

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'ENV'
        required: true
        default: 'test'
      tags:
        description: 'environment'

jobs:
  step1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Request to Baidu
        run: |
          curl https://www.baidu.com

  step2:
    runs-on: ubuntu-latest
    needs: step1
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Step 2 - Input env
        run: |
          echo "Please input env parameter (test, live, staging):"
          read env
          if [ -z "$env" ]; then
            echo "Env parameter not provided. Exiting job."
            exit 1
          fi

  step3:
    runs-on: ubuntu-latest
    needs: step2
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Step 3 - Input cid
        run: |
          echo "Please input cid parameter:"
          read cid
          if [ -z "$cid" ]; then
            echo "CID parameter not provided. Exiting job."
            exit 1
          fi
