name: Auto-manual Workflow

on:
  push:
    branches:
      - master

jobs:
  step1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Request to Baidu
        run: |
          curl https://www.baidu.com

  step2:
    runs-on: ubuntu-latest
    needs: step1
    steps:
      - name: Step 2 - Input env
        run: |
          read -p "Please input env parameter: " env
          if [ -z "$env" ]; then
            echo "EVN parameter is required."
            exit 1

  step3:
    runs-on: ubuntu-latest
    needs: step2
    steps:
      - name: Step 3 - Input cid
        run: |
          read -p "Please input cid parameter: " cid
          if [ -z "$cid" ]; then
            echo "CID parameter is required."
            exit 1
