name: Three-step Workflow

on: [push]

jobs:
  step1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Request to Baidu
        run: |
          curl https://www.baidu.com

  step2:
    runs-on: ubuntu-latest
    needs: step1
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Step 2 - Input env
        run: |
          echo "Please input env parameter (test, live, staging):"
          read env

  step3:
    runs-on: ubuntu-latest
    needs: step2
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Step 3 - Input cid
        run: |
          echo "Please input cid parameter:"
          read cid
