name: HTTP Request Action

on:
  push:
    branches:
      - '*'

jobs:
  http_request_job:
    runs-on: ubuntu-latest

    steps:
    - name: HTTP Request test
      run: curl -X GET https://www.baidu.com
